# Exercise 1.A NumPy: Manipulating Arrays

# Importing NumPy

In [1]:
import numpy as np

 # Imported NumPy library as np for easier array operations

# Looping Through Arrays
# Create arrA

In [2]:
arrA = np.array([(11, 12, 13), (14, 15, 16)])
print(arrA)

# Created a 2D NumPy array with two rows of values

[[11 12 13]
 [14 15 16]]


# Loop through first dimension

In [3]:
for x in arrA:
    print(x * 2)
    
# Multiplies each row by 2

[22 24 26]
[28 30 32]


# Loop through second dimension

In [7]:
for x in arrA:
    for y in x:
        print(y * 2)

# This loop goes element by element and multiplies each number individually.

#The first loop works on whole rows, so it prints arrays.
#The second loop works on single values, so it prints individual numbers.

22
24
26
28
30
32


# Loop result variable

In [9]:
for x in arrA:
    loop_result = x * 2
    print(loop_result)

# x is a row, so multiplying it by 2 doubles all values in that row
# Each row is multiplied at once because NumPy applies operations to the whole array automatically.

[22 24 26]
[28 30 32]


# Joining and Stacking Arrays
# Concatenate axis=0

In [10]:
joined_array_1 = np.concatenate((arrA, arrA), axis=0)
print(joined_array_1)

# This adds the arrays vertically (adds more rows).

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


# Concatenate axis=1

In [11]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

# This adds the arrays horizontally (adds more columns).

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


# Stack arrays

In [19]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

# This creates a new dimension by stacking arrays together.

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


# Stack error example

In [22]:
stacked_array_2 = np.stack((joined_array_1, joined_array_2))
print(stacked_array_2)


# Cannot concatenate because array dimensions do not match along axis 1 (different number of columns)
# This fails because the arrays do not have the same shape.

ValueError: all input arrays must have the same shape

# Another concatenate

In [23]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

# This combines arrA back into the larger array vertically.

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


# Axis=1 error

In [24]:
another_2 = np.concatenate((joined_array_1, arrA), axis=1)

# Error: arrays must have same number of rows
# This fails because the arrays do not match in shape along axis 1.

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 2

# hstack, vstack, dstack

In [25]:
h = np.hstack((arrA, arrA))
v = np.vstack((arrA, arrA))
d = np.dstack((arrA, arrA))

print(h)
print(v)
print(d)

# hstack → joins columns
# vstack → joins rows
# dstack → adds a third dimension

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


# Splitting Arrays
# Split into 2

In [ ]:
splitsky = np.array_split(joined_array_1, 2)
print(splitsky)

#This splits the array into 2 parts.

# Split into 3

In [26]:
spliterino = np.array_split(joined_array_1, 3)
print(spliterino)

#This splits the array into 3 parts.

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13]]), array([[14, 15, 16]])]


# Searching and Replacing Array Values

In [27]:
result_1 = np.where(arrA % 2 == 0, arrA, "odd")
print(result_1)

#Even numbers stay the same, odd numbers are replaced with "odd".

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


# Sorting and Filtering Arrays
# Create arrB and sort

In [28]:
arrB = np.array([[7, 6],
                 [13, 5],
                 [7, 3]])

arrB_sorted = np.sort(arrB)
print(arrB_sorted)

# Each row is sorted in ascending order.

[[ 6  7]
 [ 5 13]
 [ 3  7]]


# Filter values less than 7

In [29]:
print(arrB)

z = arrB < 7
arrC = arrB[z]

print(arrC)

# This keeps only values less than 7.

[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


# Filter values greater or equal to 7

In [30]:
y = arrB >= 7
arrD = arrB[y]

print(arrD)

# This keeps only values greater than or equal to 7.

[ 7 13  7]
