# Exercise 1.B NumPy Random

# Import NumPy

In [2]:
import numpy as np

# Imported NumPy library as np for random number generation

# Generating Random Numbers
# Random integers (size of 2)

In [3]:
r_1 = np.random.randint(1, 20, size=2)

print(r_1)

# Generated 2 random integers between 1 and 20

[16 13]


# Random integers (1 row, 2 columns)

In [4]:
r_2 = np.random.randint(1, 20, size=(1, 2))

print(r_2)

# Generated a 1x2 array of random integers

[[14  4]]


# Random floats (2 rows, 1 column)

In [5]:
r_3 = np.random.rand(2, 1)

print(r_3)

# Generated random float numbers between 0 and 1

[[0.21066256]
 [0.29376452]]


# Random integers (4 rows, 5 columns)

In [9]:
r_4 = np.random.randint(20, 100, size=(4, 5))

print(r_4)

# Generated a 4x5 array of random integers between 20 and 100

[[22 94 30 70 64]
 [52 65 86 68 63]
 [43 71 32 93 69]
 [68 98 96 77 98]]


# Random floats (4 rows, 5 columns)

In [10]:
r_5 = np.random.rand(4, 5)

print(r_5)

# Generated a 4x5 array of random float values

[[0.38597452 0.87368753 0.35467409 0.97476823 0.75253539]
 [0.03773072 0.41963169 0.34731305 0.50634457 0.85676934]
 [0.61196262 0.63548892 0.51158316 0.53113164 0.27043503]
 [0.06205128 0.66827215 0.85903749 0.46848674 0.46589999]]


# Generating Random Choices from an Array
# Create students array

In [14]:
students = np.array([
    "Eyerusalem", "Selam", "Mina", "Shewit",
    "Daniel", "Max", "Jerry", "Hiwot",
    "Nahom", "Almaz", "Noah", "Heaven"
])

print(students)

# Created a 1D array with 12 student names

['Eyerusalem' 'Selam' 'Mina' 'Shewit' 'Daniel' 'Max' 'Jerry' 'Hiwot'
 'Nahom' 'Almaz' 'Noah' 'Heaven']


# Randomly call on one student

In [15]:
call_on = np.random.choice(students)

print(call_on)

# Randomly selected one student from the array

Eyerusalem


# Create breakout groups

In [16]:
breakout_groups = np.random.choice(students, size=(3, 4))

print(breakout_groups)

# This may not be the best way to create groups because
# some students can appear more than once while others may not appear at all.
# Generated random breakout groups

[['Daniel' 'Almaz' 'Eyerusalem' 'Almaz']
 ['Nahom' 'Noah' 'Daniel' 'Heaven']
 ['Jerry' 'Noah' 'Eyerusalem' 'Eyerusalem']]


# Weighted random selections

In [17]:
call_on_weighted = np.random.choice(
    students,
    size=5,
    p=[0.30, 0.10, 0.05, 0.10,
       0.05, 0.10, 0.00, 0.05,
       0.05, 0.10, 0.05, 0.05]
)

print(call_on_weighted)

# Alex has a 30% chance of being selected.
# Michael has a 0% chance of being selected.
# Other students were given smaller probability values.
# Used weighted probabilities for random student selection

['Hiwot' 'Max' 'Almaz' 'Eyerusalem' 'Max']


# Generating a Normal Distribution

In [18]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4, 5))

print(bell_curve)

# Generated a normal distribution with mean 10 and standard deviation 5

[[ 8.7424528   5.07928371 11.36663359 10.16482757 13.73534598]
 [13.24834589  7.79818772  3.73611287  5.81266592  9.74651896]
 [23.57196626 13.70249999  6.19900495  6.17306581 10.40477567]
 [ 9.23741506 20.9806719  19.83735966  5.92646606 21.91390814]]
