# Exercise 1.C Performing operations on arrays

# Import NumPy

In [1]:
import numpy as np

# Imported NumPy as np for array operations

# Sample Arrays

In [2]:
r_1 = np.random.randint(1, 20, size=2)
r_2 = np.random.randint(1, 20, size=(1, 2))
r_3 = np.random.rand(2, 1)
r_4 = np.random.randint(20, 100, size=(4, 5))
r_5 = np.random.rand(4, 5)

print(r_1)
print(r_2)
print(r_3)
print(r_4)
print(r_5)

# Created sample random arrays for use in operations

[10 18]
[[9 6]]
[[0.87213322]
 [0.87287838]]
[[58 75 76 38 44]
 [41 59 32 78 43]
 [91 28 98 54 46]
 [25 81 69 68 98]]
[[0.32141182 0.58806683 0.6999855  0.35716583 0.66715023]
 [0.93580428 0.20176242 0.65878566 0.45338896 0.39237683]
 [0.91577449 0.59100739 0.81903476 0.29585992 0.25845776]
 [0.60719    0.96958731 0.46791127 0.89772258 0.35558717]]


# Permutations

In [6]:
print(r_4)
np.random.shuffle(r_4)
print(r_4)

# shuffle changes the array in place by rearranging rows randomly


[[25 81 69 68 98]
 [41 59 32 78 43]
 [58 75 76 38 44]
 [91 28 98 54 46]]
[[91 28 98 54 46]
 [58 75 76 38 44]
 [25 81 69 68 98]
 [41 59 32 78 43]]


In [7]:
new_shuffle = np.random.permutation(r_4)

print(new_shuffle)
print(r_4)

# permutation returns a new shuffled array and does NOT change original
# Shuffle vs permutation:
# shuffle modifies original array, permutation creates a copy

[[58 75 76 38 44]
 [91 28 98 54 46]
 [41 59 32 78 43]
 [25 81 69 68 98]]
[[91 28 98 54 46]
 [58 75 76 38 44]
 [25 81 69 68 98]
 [41 59 32 78 43]]


# Mathematical Operations
# r_1 and r_2

In [8]:
print(r_1)
print(r_2)

print(r_1.shape)
print(r_2.shape)

print(np.add(r_1, r_2))
print(np.add(r_1, r_2).shape)

# Arrays broadcast because shapes are compatible

[10 18]
[[9 6]]
(2,)
(1, 2)
[[19 24]]
(1, 2)


# r_1 and r_3

In [11]:
print(r_1)
print(r_3)

print(r_1.shape)
print(r_3.shape)

print(np.add(r_1, r_3))
print(np.add(r_1, r_3).shape)

# Broadcasting expands smaller array to match shape

[10 18]
[[0.87213322]
 [0.87287838]]
(2,)
(2, 1)
[[10.87213322 18.87213322]
 [10.87287838 18.87287838]]
(2, 2)


# r_2 and r_4

In [12]:
print(r_2)
print(r_4)

print(r_2.shape)
print(r_4.shape)

print(np.add(r_2, r_4))
print(np.add(r_2, r_4).shape)

# Broadcasting works because r_2 can expand to match r_4 rows/columns

[[9 6]]
[[91 28 98 54 46]
 [58 75 76 38 44]
 [25 81 69 68 98]
 [41 59 32 78 43]]
(1, 2)
(4, 5)


ValueError: operands could not be broadcast together with shapes (1,2) (4,5) 

# Invalid operations

In [13]:
np.add(r_1, r_4)
# Error: shapes are not compatible for broadcasting

# r_1, r_3, and r_4 cannot all broadcast together due to shape mismatch

ValueError: operands could not be broadcast together with shapes (2,) (4,5) 

# Scalar / small array broadcasting

In [14]:
print(np.add(np.array([1]), r_4))

# Scalar-like array broadcasts across all elements

[[92 29 99 55 47]
 [59 76 77 39 45]
 [26 82 70 69 99]
 [42 60 33 79 44]]


In [15]:
print(np.add(np.array([[1]]), r_4))

# 1x1 array broadcasts to full shape of r_4

[[92 29 99 55 47]
 [59 76 77 39 45]
 [26 82 70 69 99]
 [42 60 33 79 44]]


In [16]:
print(np.add(np.array([1,1,1,1,1]), r_4))

# 1D array matches columns and broadcasts across rows

[[92 29 99 55 47]
 [59 76 77 39 45]
 [26 82 70 69 99]
 [42 60 33 79 44]]


In [18]:
np.add(np.array([[1],[1]]), r_4)

# Error: shape mismatch, cannot broadcast 2x1 with 4x5 array
# Broadcasting explanation:
# NumPy expands smaller arrays to match larger shapes automatically
# The result shape is determined by the largest compatible shape

ValueError: operands could not be broadcast together with shapes (2,1) (4,5) 

# Rounding

In [19]:
print(r_3)

# Display original float values

[[0.87213322]
 [0.87287838]]


In [20]:
print(np.trunc(r_3))

# Removes decimal part (cuts off values)

[[0.]
 [0.]]


In [21]:
print(np.fix(r_3))

# Similar to trunc, removes decimals toward zero

[[0.]
 [0.]]


In [22]:
print(np.floor(r_3))

# Rounds down to nearest integer

[[0.]
 [0.]]


In [23]:
print(np.ceil(r_3))


# Rounds up to nearest integer

[[1.]
 [1.]]


In [24]:
print(np.round(r_3, 2))

# Rounds values to 2 decimal places

[[0.87]
 [0.87]]


# Cumulative Operations

In [25]:
print(r_4)

# Display r_4 for calculations

[[91 28 98 54 46]
 [58 75 76 38 44]
 [25 81 69 68 98]
 [41 59 32 78 43]]


In [26]:
print(np.sum(r_4))

# Total sum of all elements

1202


In [27]:
print(np.sum(r_4, axis=0))

# Sum of each column

[215 243 275 238 231]


In [28]:
print(np.sum(r_4, axis=1))


# Sum of each row

[317 291 341 253]


In [29]:
print(np.cumsum(r_4))

# Running total of all elements

[  91  119  217  271  317  375  450  526  564  608  633  714  783  851
  949  990 1049 1081 1159 1202]


In [30]:
print(np.cumsum(r_4, axis=0))

# Running total by column

[[ 91  28  98  54  46]
 [149 103 174  92  90]
 [174 184 243 160 188]
 [215 243 275 238 231]]


# Grocery Problem

In [31]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])

print(bag1)
print(bag2)

# Each index represents: vegetables, fruits, snacks, beverages

[2 3 4 0]
[4 0 1 2]


In [32]:
print("The first bag contains", np.sum(bag1), "items, and the second bag contains", np.sum(bag2), "items.")

The first bag contains 9 items, and the second bag contains 7 items.


In [36]:
total_categories = bag1 + bag2

print("There are", total_categories[0], "vegetables,", 
      total_categories[1], "fruits,", 
      total_categories[2], "boxes of snacks, and", 
      total_categories[3], "beverages in the two grocery bags.")

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


# Teamwork

In [38]:
ali = np.array([5, 4, 6, 4, 2])
ben = np.array([0, 5, 5, 3, 4])
carla = np.array([3, 6, 0, 3, 4])
all_knocks = np.array([ali, ben, carla])

print(all_knocks)

# Door knock data for each team member (Mon–Fri)

[[5 4 6 4 2]
 [0 5 5 3 4]
 [3 6 0 3 4]]


In [42]:
print("Ali total:", np.sum(ali))
print("Ben total:", np.sum(ben))
print("Carla total:", np.sum(carla))

print("Group total:", np.sum(all_knocks))



Ali total: 21
Ben total: 17
Carla total: 16
Group total: 54


In [43]:
daily_total = np.sum(all_knocks, axis=0)
estimated_votes = daily_total / 2

print(estimated_votes)

# Estimated votes based on rule: 2 door knocks = 1 vote

[4.  7.5 5.5 5.  5. ]
