In [3]:
# Exercise 5.A NumPy fundamentals

# in this exercise i practiced creating and working with numpy arrays
# i learned about one-dimensional, two-dimensional,
# and three-dimensional arrays using numpy

In [4]:
import numpy as np

In [5]:
# Array Basics

In [7]:
fruits = ["apple", "banana", "cherry", "date"]
arr_1 = np.array(fruits)

print(arr_1)

# i created a one-dimensional numpy array from the fruits list
# this is a regular python list containing fruit names

['apple' 'banana' 'cherry' 'date']


In [8]:
print(arr_1.dtype)

# the dtype returned is a string data type
# the letter shows the type of data stored
# the number shows the maximum length of the string

<U6


In [9]:
arr_2 = np.array([
    [10, 11, 12],
    [13, 14, 15]
])

print(arr_2)

# i created a two-dimensional array

[[10 11 12]
 [13 14 15]]


In [10]:
print(arr_2.T)

# this prints the transpose of arr_2
# using .T does not permanently change arr_2

[[10 13]
 [11 14]
 [12 15]]


In [11]:
print(arr_2)

# arr_2 is still the same after using transpose

[[10 11 12]
 [13 14 15]]


In [14]:
arr_3 = np.array([
    [1, 3, 5],
    [2, 4, 6]
])

print(arr_3)

# i created another two-dimensional array

[[1 3 5]
 [2 4 6]]


In [15]:
arr_4 = np.array([
    arr_3[0, 2],
    arr_3[1, 1]
])

print(arr_4)

# this array uses slicing/index positions from arr_3

[5 4]


In [16]:
arr_5 = np.ones((2, 2, 2))

print(arr_5)

# i created a three-dimensional array filled with ones
# each dimension contains two values

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
